CREATE DATABASE task_db;
USE task_db;

SET NAMES SJIS;

CREATE TABLE m_user(
user_id VARCHAR(24) NOT NULL PRIMARY KEY,
password VARCHAR(32) NOT NULL,
user_name VARCHAR(20) NOT NULL UNIQUE,
update_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE m_category( 
category_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
category_name VARCHAR(20) NOT NULL UNIQUE KEY,
update_datetime TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp
);

CREATE TABLE m_status(
status_code CHAR(2) NOT NULL PRIMARY KEY,
status_name VARCHAR(20) UNIQUE NOT NULL,
update_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
