CREATE DATABASE task_db;
USE DATABASE task_db;

SET NAMES SJIS;

CREATE TABLE m_user(
user_id VARCHAR(24) NOT NULL PRIMARY KEY,
password VARCHAR(32) NOT NULL,
user_name VARCHAR(20) NOT NULL UNIQUE,
update_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
